services:
  data1:
    image: nanodfs:latest
    container_name: nanodfs-data-1
    environment:
      - PORT=3000
      - PUBLIC_HOST=127.0.0.1
      - PUBLIC_PORT=4001
      - NANODFS_RUNTIME_DIR=/app/runtime
    ports:
      - "4001:3000"
    volumes:
      - data1_runtime:/app/runtime

  data2:
    image: nanodfs:latest
    container_name: nanodfs-data-2
    environment:
      - PORT=3000
      - PUBLIC_HOST=127.0.0.1
      - PUBLIC_PORT=4002
      - NANODFS_RUNTIME_DIR=/app/runtime
    ports:
      - "4002:3000"
    volumes:
      - data2_runtime:/app/runtime

volumes:
  data1_runtime:
  data2_runtime: